.github/workflows/picky-backend-ci-cd.yml, .gitignore, Dockerfile, src/main/java/com/ureca/picky_be/base/business/auth/AuthUseCase.java, src/main/resources/application.yml, src/main/resources/properties/jpa.yml, src/main/resources/properties/swagger.yml, src/test/java/com/ureca/picky_be/PickyBeApplicationTests.java
> ## 📝 관련 이슈
---
- [ID-50](https://multicampusuplus.atlassian.net/jira/software/projects/CPG/list?selectedIssue=CPG-50)
> ## 💻 작업 내용
- CI/CD 세팅
- yml 설정파일 분리 및 gitignore에 추가
---
> ## 🙇 특이 사항
- 따로 공유드린 yml파일 src/main/resources/properies에 추가 부탁드립니다.
=> [ID-50] CI/CD 구축 및 기타 수정사항

src/main/java/com/ureca/picky_be/jpa/movie/Playlist.java
> ## 📝 관련 이슈
---
- [[ID-96] PlayList -> Playlist로 Refact](https://multicampusuplus.atlassian.net/browse/CPG-96)
> ## 💻 작업 내용
- PlayList -> Playlist로 Refact
---
> ## 🙇 특이 사항
- 
---
> ## 👻 리뷰 요구사항 (선택)
- 
---
=> ID-96 PlayList에서 Playlist로 리팩토링

src/test/java/com/ureca/picky_be/PickyBeApplicationTests.java, src/test/java/com/ureca/picky_be/base/business/NaverServiceTest.java, src/test/java/com/ureca/picky_be/base/presentation/controller/OAuth2ControllerTest.java, src/test/java/com/ureca/picky_be/base/presentation/web/JwtTokenProviderTest.java
> ## 📝 관련 이슈
---
- [ID-#](url)
> ## 💻 작업 내용
- 
---
> ## 🙇 특이 사항
- 
---
> ## 👻 리뷰 요구사항 (선택)
- 
---
=> test: 테스트 코드 주석처리

.github/workflows/picky-backend-ci-cd.yml, .gitignore, src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java, src/main/java/com/ureca/picky_be/base/business/auth/OAuth2UseCase.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUserReq.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/OAuth2Token.java, src/main/java/com/ureca/picky_be/base/implementation/auth/GoogleManager.java, src/main/java/com/ureca/picky_be/base/implementation/auth/NaverManager.java, src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java, src/main/java/com/ureca/picky_be/config/oAuth2/GoogleConfig.java, src/main/resources/application.yml
> ## 📝 관련 이슈
---
- [ID-28](https://multicampusuplus.atlassian.net/jira/software/projects/UP/boards/9/timeline)
> ## 💻 작업 내용
- 구글 소셜 로그인 구현
- 네이버 소셜 로그인 로직상 오류 수정
- OAuth2 로직 SRP 원칙에 맞게 수정
---
> ## 🙇 특이 사항
- 이전 이슈에서 부족했던 네이버 소셜 로그인 테스트까지 완료했습니다. 현재 구글, 네이버 소셜 로그인 정상작동합니다.
---
=> [ID-28] 구글 소셜 로그인

.github/workflows/create-jira-issue.yml
> ## 📝 관련 이슈
---
- [ID-#](url)
> ## 💻 작업 내용
- 
---
> ## 🙇 특이 사항
- 
---
> ## 👻 리뷰 요구사항 (선택)
- 
---
=> [BE] dev 브랜치 변경

src/main/java/com/ureca/picky_be/jpa/board/Board.java, src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java, src/main/java/com/ureca/picky_be/jpa/board/BoardContent.java, src/main/java/com/ureca/picky_be/jpa/following/Follow.java, src/main/java/com/ureca/picky_be/jpa/genre/Genre.java, src/main/java/com/ureca/picky_be/jpa/linereview/LineReview.java, src/main/java/com/ureca/picky_be/jpa/linereview/LineReviewLike.java, src/main/java/com/ureca/picky_be/jpa/movie/FilmCrew.java, src/main/java/com/ureca/picky_be/jpa/movie/MovieGenre.java, src/main/java/com/ureca/picky_be/jpa/movie/MoviePlayList.java, src/main/java/com/ureca/picky_be/jpa/platform/Platform.java, src/main/java/com/ureca/picky_be/jpa/report/Report.java, src/main/java/com/ureca/picky_be/jpa/user/Status.java, src/main/java/com/ureca/picky_be/jpa/user/User.java, src/main/java/com/ureca/picky_be/jpa/user/UserGenrePreference.java
> ## 📝 관련 이슈
---
- [ID-43](https://multicampusuplus.atlassian.net/browse/UP-43)
- #17 
> ## 💻 작업 내용
- 게시글(Board) 분야 수정
- 한줄평(LineReview) 분야 수정
- 장르(Genre) 분야 수정
- 영화(Movie) 분야 수정
- 신고(Report) 분야 수정
- 유저(User) 분야 수정
---
> ## 🙇 특이 사항
- 분명 뭔가 반대로 했거나 이상한 연관관계들이 있을 수도 있어서 꼼꼼히 검토 부탁드려요
---
> ## 👻 리뷰 요구사항 (선택)
- 
---
=>  [BE] UP-43 엔티티 및 연관관계 수정

build.gradle, src/main/java/com/ureca/picky_be/global/exception/CustomException.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/exception/GlobalExceptionHandler.java, src/main/java/com/ureca/picky_be/global/response/ApiResponse.java, src/main/java/com/ureca/picky_be/global/response/ApiResponseAdvice.java, src/main/java/com/ureca/picky_be/global/response/ErrorResponse.java
- [UP-29] (https://multicampusuplus.atlassian.net/jira/software/projects/UP/boards/9/timeline?selectedIssue=UP-29)
</br>
- 공통 응답 코드 구현
- ResponseBodyAdvice 사용하여 전역적으로 응답 코드 포맷 생성
</br>
- ResponseBodyAdvice 사용하여 전역적으로 응답 코드 포맷 생성
</br>
- 
</br>
=> [BE][UP-29] 공통 응답 코드 구현

src/main/java/com/ureca/picky_be/global/response/ApiResponse.java, src/main/java/com/ureca/picky_be/global/response/ApiResponseAdvice.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
- [UP-54](https://multicampusuplus.atlassian.net/jira/software/projects/UP/boards/9/timeline?selectedIssue=UP-54)
</br>
- 성공 코드 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-54] 성공 코드 구현

.gitignore, src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java, src/main/java/com/ureca/picky_be/base/business/auth/OAuth2UseCase.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/DeleteUserReq.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUrlResp.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUserResp.java, src/main/java/com/ureca/picky_be/base/implementation/auth/GoogleManager.java, src/main/java/com/ureca/picky_be/base/implementation/auth/KakaoManager.java, src/main/java/com/ureca/picky_be/base/implementation/auth/NaverManager.java, src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/config/oAuth2/GoogleConfig.java, src/main/java/com/ureca/picky_be/config/oAuth2/KakaoConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/response/ApiResponseAdvice.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/global/web/CustomUserDetailsService.java, src/main/java/com/ureca/picky_be/global/web/JwtAuthenticationFilter.java, src/main/java/com/ureca/picky_be/global/web/JwtProperties.java, src/main/java/com/ureca/picky_be/global/web/JwtTokenProvider.java, src/main/java/com/ureca/picky_be/global/web/LocalJwtDto.java, src/main/resources/application.yml, src/main/resources/properties/swagger.yml
> ## 📝 관련 이슈
- [UP-45](https://multicampusuplus.atlassian.net/jira/software/projects/UP/boards/9/timeline?selectedIssue=UP-45)
> ## 💻 작업 내용
- 소셜로그인 회원탈퇴 구현
> ## 🙇 특이 사항
- 죄송하지만 이번에도 설정파일 수정이 있기때문에 다시 받아주셔야겠습니다,,
=> [BE] UP-45 소셜 로그인 회원 탈퇴 구현

src/main/java/com/ureca/picky_be/base/implementation/auth/AuthManager.java, src/main/java/com/ureca/picky_be/jpa/user/Role.java
- [UP-63](https://multicampusuplus.atlassian.net/jira/software/projects/UP/boards/9/timeline?selectedIssue=UP-63)
</br>
- jwt정보 추출 간편화
</br>
- 사용법 세미나 엽니다
</br>
- 
</br>
=> [BE][UP-63] jwt정보 추출 간편화

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeUseCase.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CountLineReviewLikeResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewLikeReq.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewLikeResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewReq.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/UpdateLineReviewReq.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/UpdateLineReviewResp.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewLikeMapper.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewMapper.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewLikeRepository.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/jpa/lineReview/LineReview.java, src/main/java/com/ureca/picky_be/jpa/lineReview/LineReviewLike.java, src/main/java/com/ureca/picky_be/jpa/lineReview/Preference.java, src/main/java/com/ureca/picky_be/jpa/linereview/Preference.java, src/main/java/com/ureca/picky_be/jpa/user/UserGenrePreference.java
- [UP-61] #36 
</br>
- 한줄평 & 한줄평 좋아요 CREATE, UPDATE, COUNT 구현
</br>
- 좋아요 count는 그냥 한번 넣어봤습니다.
- Read, Delete는 기능이 많을 것 같아, 이슈를 새로 생성하겠습니다!
</br>
- 
</br>
=> [UP-67][BE] 한줄평 & 한줄평 좋아요 CREATE, UPDATE, COUNT 구현 

src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java, src/main/java/com/ureca/picky_be/jpa/linereview/LineReviewSoftDelete.java
- [UP-#] #39 
</br>
-  fix: 한줄평 & 한줄평 좋아요 CREATE, UPDATE, COUNT 구현
</br>
-  fix: 한줄평 & 한줄평 좋아요 CREATE, UPDATE, COUNT 구현
</br>
- 
</br>
=> [BE][UP-61] fix: 한줄평 & 한줄평 좋아요 CREATE, UPDATE, COUNT 구현

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewLikeRepository.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/FilmCrewRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/GenreRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieBehindVideoRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieGenreRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movieworker/MovieWorkerRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-75] #46 
</br>
- 영화 등록 api
- 영화 상세 정보 get api
- 오타 수정 및 보안파일 임시 설정
</br>
- 4시간 반만에 끝냈어요 칭찬해주세요
</br>
- 
</br>
=> [BE][UP-75] 영화 Create / Read API

src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java
- [UP-#] #53 
</br>
- 한줄평 & 한줄평 좋아요 READ 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-66]  한줄평 & 한줄평 좋아요 READ 수정

src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
- [UP-#] #56 
</br>
- 한줄평 & 한줄평 좋아요 READ lastCreatedAt 커서 추가
</br>
- 추후에 리펙토링 시, 인덱스 추가 및 좋아요 카운트 테이블 생성
</br>
- 
</br>
=> [BE][UP-85] 한줄평 & 한줄평 좋아요 READ lastCreatedAt 커서 추가

src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardManagingService.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardContentRepository.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/jpa/board/Board.java, src/main/java/com/ureca/picky_be/jpa/board/BoardContent.java
- [UP-49] #26 
</br>
- 게시글 UPDATE 구
</br>
- 
</br>
- 
</br>
=> [BE][UP-49] 게시글 Update 구현

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/business/board/dto/UpdateBoardReq.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/jpa/board/Board.java
- [UP-49] #49 
</br>
- Board 업데이트 글 내용과 스포일러 여부만 수정되도록 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-49] Board Update 내용(Context)와 스포일러 여부(isSpoiler)만 수정되도록 수정

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java
- [UP-110] #67 
</br>
- Create 시 로그인한 사람 닉네임으로 저장되도록 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-110] 작성자 필드 추가되도록 구현

src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java
- [UP-111] #70 
</br>
- 소셜로그인 프론트 연결 version2
</br>
- 
</br>
- 
</br>
=> [BE][UP-11] 소셜로그인 프론트 연결 version2

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardContentPOJO.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardContentProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/GetBoardInfoResp.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-49] #49 
</br>
- 영화에 대한 무비로그들, 최신순으로 10개씩 조회하는 API 구현 
</br>
- 
</br>
- 
</br>
=> [BE][UP-49] 영화에 대한 무비로그 조회 API 구현

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
- [UP-49] #49 
</br>
- 최신 무비로그들 10개씩 호출하는 API 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-49] 최신 무비로그 조회 API 구현

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/MoviePreferenceResp.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetMoviesForRegisReq.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetMoviesForRegisResp.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetNicknameValidationResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
- [UP-117] #73 
</br>
- 닉네임 중복검사
- 회원가입시 영화 리스트 전송 api
</br>
- 브랜치 지우지 마세요
</br>
=> [BE][UP-117] 닉네임 중복검사, 회원가입시 영화 리스트 전송 api

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/board/Board.java, src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java, src/main/java/com/ureca/picky_be/jpa/config/IsDeleted.java, src/main/java/com/ureca/picky_be/jpa/lineReview/LineReview.java, src/main/java/com/ureca/picky_be/jpa/movie/Movie.java, src/main/java/com/ureca/picky_be/jpa/user/User.java
- [UP-125] #78 
</br>
- 게시글 삭제(논리적 삭제) 기능 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-125] 게시글 삭제 API 구현

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/DeleteBoardResp.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetMovieRelatedBoardsResp.java, src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/AddBoardCommentResp.java, src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/DeleteBoardCommentsResp.java, src/main/java/com/ureca/picky_be/base/business/board/dto/contentDto/GetBoardContentsResp.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardCommentRepository.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
- [UP-126] #80 
</br>
- 댓글 삭제 기능 
</br>
- 
</br>
- 
</br>
=> [BE][UP-126] 댓글 삭제 API 구현

src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java
- [UP-133] #83 
</br>
- PathVariable과 RequestParam의 용도에 맞춰서 BoardController 수정했습니다.
</br>
- 
</br>
- 
</br>
=> [BE][UP-133] BoardController pathvariable, requestparam 수정

src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/config/WebConfig.java
- [UP-134] #85 
</br>
- Spring Security 경로 허용 및 preflight 설정
</br>
- 당분간 무단 머지 좀 하겠습니다...
</br>
- 
</br>
=> [BE][UP-134] Spring Security 경로 허용 및 preflight 설정

src/main/java/com/ureca/picky_be/config/SecurityConfig.java
- [UP-134] #85 
</br>
- 보안 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-134] 보안 수정

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardLikeRepository.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/board/BoardLike.java
- [UP-132] #82 
</br>
- API 1개로 좋아요 생성, 취소 기능 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-132] 게시글 좋아요 기능 구현

src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java
- [UP-132] #89 
</br>
- 보안 설정 (닉네임 중복 검사)
</br>
- 보안 설정 (닉네임 중복 검사)
</br>
- 
</br>
=> [BE][UP-132] 보안 설정 (닉네임 중복 검사)

src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistUseCase.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/GetPlaylistProjection.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/GetPlaylistResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/playlist/PlaylistRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/playlist/PlaylistController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-123] 
</br>
- 플레이리스트 조회 구현
- 플레이리스트 3개씩 페이징, 최신순
</br>
- #누르고 제 이슈 검색이 안 되네여 아마 내가 며칠 전에 잘못 날린 커밋 때문이겠지..
</br>
- 플리 기능 5개 중에 하나 구현했어요 파일 체인지 13개지만 최소 단위입니다 ㅎ
</br>
=> [BE][UP-123] 플레이리스트 조회

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistUseCase.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistReq.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistResp.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistReq.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/playlist/MoviePlaylistRepository.java, src/main/java/com/ureca/picky_be/base/persistence/playlist/PlaylistRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/admin/AdminPlaylistController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/playlist/PlaylistController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/playlist/Playlist.java
- [UP-123] #76 
</br>
- 플레이리스트 추가를 위한 영화 리스트 페이지네이션 조회 구현
- 플레이리스트 추가 기능 구현
- 플레이리스트 수정
- 플레이리스트 삭제
</br>
- 
</br>
- 
</br>
=> [BE][UP-123] 플레이리스트 추가를 위한 영화 리스트 페이지네이션 조회, 플레이리스트 추가

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java, src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistUseCase.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistReq.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/AddPlaylistResp.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistReq.java, src/main/java/com/ureca/picky_be/base/business/playlist/dto/UpdatePlaylistResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/FilmCrewRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieGenreRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/playlist/MoviePlaylistRepository.java, src/main/java/com/ureca/picky_be/base/persistence/playlist/PlaylistRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/admin/AdminPlaylistController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/playlist/PlaylistController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/movie/FilmCrew.java, src/main/java/com/ureca/picky_be/jpa/movie/MovieGenre.java, src/main/java/com/ureca/picky_be/jpa/movie/MoviePlaylist.java, src/main/java/com/ureca/picky_be/jpa/platform/Platform.java, src/main/java/com/ureca/picky_be/jpa/playlist/Playlist.java
- [UP-144] #94 
</br>
- 엔티티에 다른 엔티티로 연관관계 매핑이 되어있는데도 변수명이 movieId인 경우가 많았습니다. 그래서 영화 아이디를 조회하려면 playlist.movieId.id 이런식으로 들어가야하는 경우가 많았어서 관련된 부분 리팩토링 했습니다.
- moviePlayList였던 부분 moviePlaylist로 수정하여 통일했습니다.
</br>
- 웬만한 부분은 제가 테스트 해보고 정상작동 하는 거 보고 올리기는하지만, Repo 쿼리 부분에 들어있는 건 발견 못하고 지나쳤을 수도 있습니다. 당분간 실행했는데 작동을 안 하면 레포 레이어에서 movieId랑 관련된 부분에 오류가 있는지 봐주시면 될 것 같습니다.
- 왜 이런 대공사를 지금하냐?라는 의문이 드실 수 있습니다. 근데 .. 작업해보시면 아시겠지만.. 상당히 헷갈린답니다 😭
- 브랜치를 이전에 제가 작업하던 브랜치에서 따왔습니다. 그래서 머지 순서는 이전 pr 다음 이 pr입니다. 순서가 지켜지지 않으면 깃의 요정이 ... 🧚
</br>
- 
</br>
=> [BE][UP-144] entity refactoring

.github/workflows/picky-backend-ci-cd.yml, .gitignore, src/main/java/com/ureca/picky_be/base/presentation/controller/TempController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/resources/application.yml
- [UP-#](url)
</br>
- 서버 대 서버로 소셜로그인 api가 연결됨에 따라 로컬에서 토큰을 발급받을 수 있는 수단이 사라짐 이를 위해 임시로 토큰을 발급받을 수 있도록 함 및 약간의 보안 추가
</br>
- 
</br>
- 
</br>
=> [BE][UP-out_of_number] 임시 토큰 발급 api

.github/workflows/picky-backend-ci-cd.yml, .gitignore, build.gradle, src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/AddBoardReq.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/ImageManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/VideoManager.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/presentation/ContentController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/TempController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/config/S3Config.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/config/SwaggerConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/web/JwtTokenProvider.java, src/main/java/com/ureca/picky_be/jpa/board/BoardContentType.java, src/main/resources/application.yml
- [UP-146] #96 
</br>
- 영상&사진 업로드 인프라 구축
- board에 사진&영상 업로드 로직 추가
- swagger 제목 귀엽게 수정
- jwt filter에 예외처리 추가
</br>
- 6개의 태스크중 2개일 뿐입니다 . .
</br>
- 
</br>
=> [BE][UP-146] 영상&사진 업로드 인프라 구축 및 board에 사진&영상 업로드 로직 추가

src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetUserResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java, src/main/java/com/ureca/picky_be/base/presentation/controller/auth/OAuth2Controller.java
- [UP-146] #99 
</br>
- 유저 정보 조회할 때 이메일 가져오기
</br>
- 
</br>
- 
</br>
=> [BE][UP-146] 유저 정보 조회할 때 이메일 가져오기

src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/TokenResp.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetUserResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/OAuth2DtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java
- [UP-146] #102 
</br>
- 회원가입 절차 단순화
- 로그인시 유저 role 반환
- 유저 조회시 presignUrl로 프로필 전송
</br>
- 
</br>
- 
</br>
=> [BE][UP-146] 회원가입 절차 단순화, 로그인시 유저 role 반환, 유저 조회시 presignUrl로 프로필 전송

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/jpa/user/User.java
- [UP-146] #103 
</br>
- 무비로그 유효성 검사 추가
- 닉네임과 프로필 사진만 변경 가능한 api
</br>
- 
</br>
- 
</br>
=> [BE][UP-146] 무비로그 유효성 검사 추가, 닉네임과 프로필 사진만 변경 가능한 api

src/main/java/com/ureca/picky_be/base/business/auth/GoogleService.java, src/main/java/com/ureca/picky_be/base/business/auth/KakaoService.java, src/main/java/com/ureca/picky_be/base/business/auth/NaverService.java, src/main/java/com/ureca/picky_be/base/business/auth/dto/LoginUserInfo.java, src/main/java/com/ureca/picky_be/base/implementation/auth/GoogleManager.java, src/main/java/com/ureca/picky_be/base/implementation/auth/KakaoManager.java, src/main/java/com/ureca/picky_be/base/implementation/auth/NaverManager.java
- [UP-#](url)
</br>
- 
</br>
- 
</br>
- 
</br>
=> [BE][UP-146] 소셜로그인 수정

src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java, src/main/java/com/ureca/picky_be/config/S3Config.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-146] #106 
</br>
- S3설정 수정 
- ec2에 경로 생성해서 오류 해결했습니다
</br>
- 
</br>
- 
</br>
=> [BE][UP-146] S3설정 수정

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetUserLikeMovieReq.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetUserLikeMovieResp.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieLikeRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-162] #109 
</br>
- 마이페이지 닉네임을 활용해 사용가자 좋아요 누른 영화들 조회 API 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-162] 마이페이지 좋아요 누른 영화들 조회 API 구현

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/BoardUseCase.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/BoardMovieIdQueryReq.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/board/BoardController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/jpa/board/BoardComment.java
- [UP-172] #115 
</br>
- Board 무한스크롤링 기능들 Cursor 기반 페이징 기법으로 리팩토링
- 게시글 댓글 조회, 최신 게시글들 조회, 특정 영화에 대한 최신 게시글들 조회
</br>
- 
</br>
- 
</br>
=> [BE][UP-172] Board 무한 스크롤링 Cursor 기반으로 리팩토링

src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java
- [UP-172] #115 
</br>
- Playlist getPlaylistProjections에서 lastPlayListId에 대한 Validation 추가
</br>
- 
</br>
- 
</br>
=> [BE][UP-172] PlayList Cursor 페이징 Validation 추가

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
- [UP-174] #118 
</br>
- 장르별 영화 모아보기 무한스크롤 List -> Slice로 변경
</br>
- 
</br>
- 
</br>
=> [BE][UP-174] 장르별 영화 모아보기 무한스크롤 List -> Slice로 변경

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java, src/main/java/com/ureca/picky_be/jpa/platform/PlatformType.java
- [UP-175] #120 
</br>
- 영화 등록시 영화 플랫폼도 함께 입력 받기
</br>
- 
</br>
- 
</br>
=> [BE][UP-175] 영화 등록시 영화 플랫폼도 함께 입력 받기

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/UpdateMovieReq.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-175] #123 
</br>
- 영화 수정에 상영 플랫폼 추가 및 영화 이미 존재하면 다시 추가 막기
</br>
- 
</br>
- 
</br>
=> [BE][UP-175] 영화 수정에 상영 플랫폼 추가 및 영화 이미 존재하면 다시 추가 막기

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/PlatformRepository.java
- [UP-175] #124 
</br>
- 영화 상세 조회에 플랫폼 정보 추가
</br>
- 
</br>
- 
</br>
=> [BE][UP-175] 영화 상세 조회에 플랫폼 정보 추가

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
- [UP-181] #126 
</br>
- 영화 상세페이지에 총평점 추가
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 영화 상세페이지에 총평점 추가

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-181] #127 
</br>
- 무비로그 조회시 작성자의 프로필 조회하는 presign url 설정
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 무비로그 조회시 작성자의 프로필 조회하는 presign url 설정

src/main/java/com/ureca/picky_be/jpa/recommend/Recommend.java
- [UP-#] #129 
</br>
- Recommend entity 생성
</br>
- Recommend entity 생성
</br>
- 
</br>
=> [BE][UP-183] Recommend entity 생성

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GenderLineReviewProjection.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetLineReviewGenderInfoResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/GetLineReviewRatingInfoResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/RatingLineReviewProjection.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-176] #121 
</br>
-  영화 평점 점수 비율
-  남녀별 평균 평점
-  성별별 한줄평 작성자 수 및 관람 비율
</br>
- 
</br>
- 
</br>
=> [BE][UP-176] 영화 상세페이지 한줄평 요약 정보 조회 API

src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java
- [UP-187] #132 
</br>
- Swagger 추가
</br>
- 
</br>
- 
</br>
=> [BE][UP-187] 한줄평 요약 정보 API Swagger 설명 추가

.github/workflows/picky-backend-ci-cd.yml, .gitignore, src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieAuto.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/AddMovieReq.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/implementation/content/ImageManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/VideoManager.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/persistence/movie/RecommendRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java, src/main/java/com/ureca/picky_be/jpa/movie/Movie.java, src/main/resources/application.yml
- [UP-181] 
</br>
- 추천목록 조회해 영화 자동 등록 및 프로필 수정 로직 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 추천목록 조회해 영화 자동 등록 및 프로필 수정 로직 수정

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardCommentProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java, src/main/java/com/ureca/picky_be/base/business/board/dto/commentDto/GetAllBoardCommentsResp.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
- [UP-189] #134 
</br>
- 리뷰(게시글, 한줄평, 댓글) 조회 API에서 각 API별 작성자 여부 판단 필드 추가
</br>
- 잘 확인해주세요
</br>
- 
</br>
=> [BE][UP-189] 리뷰 조회시 isAuthor response 추가

.gitignore, build.gradle, src/main/java/com/ureca/picky_be/base/business/email/MailService.java, src/main/java/com/ureca/picky_be/base/business/email/MailUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/email/EmailManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/email/EmailController.java, src/main/java/com/ureca/picky_be/config/MailConfig.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/resources/application.yml
- [UP-email] #138 
</br>
- 이메일 전송 기능 구현
- 현재 보내는 내용은 하드코딩되어있으나 추후 수정 가능
- userId를 파라미터로 받습니다.
</br>
- 
</br>
- 
</br>
=> [BE][UP-email] 이메일 전송 기능 구현

.github/workflows/picky-backend-ci-cd.yml, .gitignore, docker-compose.yml, src/main/java/com/ureca/picky_be/global/exception/GlobalExceptionHandler.java
- [UP-#] #111 
</br>
- 엘라스틱 서치 환경 설정
- SSH 인증 방식 구현
</br>
- kibana 사용시 Https 로 접속!
</br>
- 
</br>
=> [BE][UP-167] 엘라스틱 서치 환경 설정

src/main/java/com/ureca/picky_be/base/business/user/UserService.java
- [UP-181] 
</br>
- 닉네임 로직 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 닉네임 로직 수정

src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
- [UP-181] 
</br>
- 프로필 변경
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 프로필 변경

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieBehindVideoRepository.java, src/main/java/com/ureca/picky_be/jpa/entity/movie/Movie.java
- [UP-181]
</br>
- 영화 수정 로직 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 영화 수정 로직 수정

src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java, src/main/java/com/ureca/picky_be/base/business/notification/NotificationUseCase.java, src/main/java/com/ureca/picky_be/base/business/notification/dto/CreateNotificationResp.java, src/main/java/com/ureca/picky_be/base/business/notification/dto/NotificationProjection.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java, src/main/java/com/ureca/picky_be/base/persistence/notification/NotificationRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/notification/NotificationController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
- [UP-email] #138 
</br>
- 사용자 미확인 알림들 무한 스크롤 형태로 읽기 구현
- 알림 읽으면 해당 알림 읽음 업데이트
</br>
- 
</br>
- 
</br>
=> [BE][UP-email] 알림들 조회 및 읽음 업데이트 API 개발

build.gradle, src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSearchMoviesResp.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/UserUseCase.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetSearchUsersResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/UserDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieSearchRepository.java, src/main/java/com/ureca/picky_be/base/persistence/user/UserSearchRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/config/ElasticSearchConfig.java, src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java, src/main/java/com/ureca/picky_be/elasticsearch/document/user/UserDocument.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java
- [UP-#] #139 
</br>
- 유저 Elastic search 조회
- 영화 Elastic search 조회
- 유저 등록 및 수정시 Elastic search 등록
- 영화 등록시 Elastic search 등록
</br>
- 
</br>
- 
</br>
=> [BE][UP-elastic] 유저, 영화 Elastic search

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
- [UP-181]
</br>
- 추천에 따른 영화 자동 저장 로직 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-181] 추천에 따른 영화 자동 저장 로직 수정

src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java, src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
- [UP-SSE] #150 
</br>
- 연결시 보내는 메세지 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-SSE] SSE 연결 메세지 수정

src/main/java/com/ureca/picky_be/base/business/follow/FollowService.java, src/main/java/com/ureca/picky_be/base/business/follow/FollowUseCase.java, src/main/java/com/ureca/picky_be/base/business/follow/dto/FollowProjection.java, src/main/java/com/ureca/picky_be/base/business/follow/dto/GetFollowUserResp.java, src/main/java/com/ureca/picky_be/base/implementation/follow/FollowManager.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/entity/follow/Follow.java
- [UP-Follow] #153 
</br>
- 팔로우 Create/Delete (팔로우 관계가 없으면 Create, 있으면 Delete)
- 닉네임을 통한 팔로잉하고 있는 사람들 Read, 팔로우하고 있는 사람들 Read
</br>
- userId를 넘기지 않기 위해 마이페이지에서 nickname으로 넘겨서 값을 받아오도록 설계했습니다.
- Create/Delete에 대해 예외처리를 해뒀으나 추후 테스트를 진행하며 추가적인 예외처리를 고민해봐야합니다.
</br>
- 
</br>
=> [BE][UP-Follow] 팔로우 CRUD 기능

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewLikeUseCase.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/CreateLineReviewLikeReq.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetMyPageUserInfoResp.java, src/main/java/com/ureca/picky_be/base/business/user/dto/UserInfoProjection.java, src/main/java/com/ureca/picky_be/base/implementation/board/BoardManager.java, src/main/java/com/ureca/picky_be/base/implementation/content/ProfileManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/persistence/user/UserRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewLikeController.java, src/main/java/com/ureca/picky_be/base/presentation/controller/user/UserController.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java, src/main/java/com/ureca/picky_be/jpa/entity/lineReview/LineReviewLike.java
- [UP-LineReview] #157 
</br>
- 마이페이지 닉네임 및 사용자 정보 조회 수정
- 마이페이지 한줄평 닉네임으로 조회 API, isAuthor 항상 true 인거 수정
- 한줄평 Builder 리팩토링
- 한줄평 좋아요/싫어요 생성 및 취소 구현
- 무비로그 관련해서 User Role 구현
</br>
- 
</br>
- 
</br>
=> [BE][UP-LineReview] 한줄평 관련 수정

src/main/java/com/ureca/picky_be/base/implementation/user/UserManager.java
- [UP-Follow] 
</br>
- 마이페이지 조회시 해당 사용자 Following Count 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-Follow] following Count 수정

src/main/java/com/ureca/picky_be/base/business/user/UserService.java
- [UP-Follow]
</br>
- 팔로우, 팔로잉 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-Follow] 팔로워, 팔로잉 카운트 수정

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewUseCase.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewLikeManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/lineReview/LineReviewController.java, src/main/java/com/ureca/picky_be/global/exception/ErrorCode.java, src/main/java/com/ureca/picky_be/global/success/SuccessCode.java
- [UP-#](url) #160 
</br>
- 한줄평 삭제 구현
</br>
- 한줄평 삭제 구현
</br>
- 
</br>
=> [BE][UP-linereview-feat] 한줄평 삭제 구현

src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java, src/main/java/com/ureca/picky_be/config/SecurityConfig.java
- [UP-follow]
</br>
- 
</br>
- 
</br>
- 
</br>
=> [BE][UP-follow] Follow API Security Config 추가

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/mapper/LineReviewDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
- [UP-#](url) #164 
</br>
- 한줄평 좋아요 싫어요 여부 확인
</br>
- 한줄평 좋아요 싫어요 여부 확인
</br>
- 
</br>
=> [BE][UP-linereview-feat] 한줄평 좋아요 싫어요 여부 확인

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/notification/NotificationEventListener.java, src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java, src/main/java/com/ureca/picky_be/base/business/notification/NotificationUseCase.java, src/main/java/com/ureca/picky_be/base/business/notification/dto/NotificationProjection.java, src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java, src/main/java/com/ureca/picky_be/base/persistence/notification/NotificationRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/notification/NotificationController.java
- [UP-LineReview] 
</br>
- 알림 조회 및 실시간 알림 사용자 프로필 URL 수정
- 테스트 알림 API Null 에러 수정
- 마이페이지 게시글 프로필 URL 수정
</br>
- Url 변환에 있어서 Service가 많이 지저분해졌습니다. 추후 리팩토링 필요
</br>
- 
</br>
=> [BE][UP-LineReview] 마이페이지 게시글들 및 알림 S3 URL 수정

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetRecommendMovieProjection.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetRecommendMovieResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java
- [UP-#](url) #167 
</br>
- 추천 목록 플랫폼, 장르 반환
</br>
- 추천 목록 플랫폼, 장르 반환
</br>
- 
</br>
=> [BE][UP-recommend-feat] 추천 목록 플랫폼, 장르 반환

src/main/java/com/ureca/picky_be/base/business/movie/dto/GetPlatform.java
- [UP-#](url) #167 
</br>
-   추천 목록 플랫폼, 장르 반환 파일 추가
</br>
-   추천 목록 플랫폼, 장르 반환 파일 추가
</br>
-   추천 목록 플랫폼, 장르 반환 파일 추가
</br>
=> [BE][UP-recommend-feat]  추천 목록 플랫폼, 장르 반환 파일 추가

src/main/java/com/ureca/picky_be/base/business/user/UserService.java, src/main/java/com/ureca/picky_be/base/business/user/dto/GetMyPageUserInfoResp.java, src/main/java/com/ureca/picky_be/base/implementation/follow/FollowManager.java, src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java
- [UP-Follow] 
</br>
- 마이페이지 닉네임으로 상대 페이지 조회시, 사용자 팔로우 여부 return
</br>
- 
</br>
- 
</br>
=> [BE][UP-Follow] Mypage 닉네임으로 데이터 조회시 isFollowing return

src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java, src/main/java/com/ureca/picky_be/elasticsearch/document/user/UserDocument.java
- [UP-fix] 
</br>
- 엘라스틱서치와 mysql 자동 동기화
</br>
- 
</br>
- 
</br>
=> [BE][UP-fix] 엘라스틱서치와 mysql 자동 동기화

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetMovieDetailResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java
- [UP-#](url) 영화상세페이지 한줄평 토탈 반환
</br>
-  영화상세페이지 한줄평 토탈 반환
</br>
-  영화상세페이지 한줄평 토탈 반환
</br>
- 
</br>
=> [BE][UP-linereview-fix] 영화상세페이지 한줄평 토탈 반환

src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
- [UP-#](url) 영화상세페이지 한줄평 토탈 반환 수정
</br>
- 영화상세페이지 한줄평 토탈 반환 수정
</br>
- 영화상세페이지 한줄평 토탈 반환 수정
</br>
- 
</br>
=> [BE][UP-linereview-fix] 영화상세페이지 한줄평 토탈 반환 수정

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
- [UP-#](url)
</br>
- 
</br>
- 
</br>
- 
</br>
=> [BE][UP-fix] 날라간 파일 찾아옴

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/MovieUseCase.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/movie/MovieController.java, src/main/java/com/ureca/picky_be/jpa/entity/movie/Movie.java
- [UP-191]
</br>
- 장르별 영화 조회 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] 장르별 영화 조회 수정

src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java
- [UP-191] #177 
</br>
- 트레일러, ost 수정되지 않는 문제 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] 트레일러, ost 수정되지 않는 문제 수정

src/main/java/com/ureca/picky_be/base/business/playlist/PlaylistService.java, src/main/java/com/ureca/picky_be/base/implementation/playlist/PlaylistManager.java, src/main/java/com/ureca/picky_be/jpa/entity/playlist/Playlist.java
- [UP-191] #180 
</br>
- 플레이리스트 제목 수정 안 되는 문제 해결
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] 플레이리스트 제목 수정 안 되는 문제 해결

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/AddBoardReq.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java
- [UP-191] #177 
</br>
- 무비로그 사진 및 영상 업로드 로직 수정 (사진 or 동영상이 하나 이상 존재하도록)
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] 무비로그 사진 및 영상 업로드 로직 수정 (사진 or 동영상이 하나 이상 존재하도록)

src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
- [UP-193] #184 
</br>
- 무비로그 조회 관련 API들 movieId return 되도록 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-193] 게시글 조회 관련해서 movieId 추가

src/main/java/com/ureca/picky_be/base/business/notification/NotificationService.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/NotificationDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/notification/NotificationManager.java
- [UP-195] #187 
</br>
- 알림 관련 createdAt 알림의 생성시간으로 전부 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-195] 알림 createdAt 로 수정

src/main/java/com/ureca/picky_be/base/business/notification/NotificationEventListener.java, src/main/java/com/ureca/picky_be/base/business/notification/dto/BoardCreatedEvent.java, src/main/java/com/ureca/picky_be/base/implementation/email/EmailManager.java, src/main/java/com/ureca/picky_be/config/AsyncConfig.java, src/main/resources/application.yml
- [UP-190] #189 
</br>
- Security Context 전략 수정을 통한 비동기 오류 해결
</br>
- 
</br>
- 
</br>
=> 알림 Listener 비동기 전략 수정

src/main/java/com/ureca/picky_be/base/business/email/MailService.java, src/main/java/com/ureca/picky_be/base/business/email/MailUseCase.java, src/main/java/com/ureca/picky_be/base/presentation/controller/email/EmailController.java
- [UP-197] #191 
</br>
- 이메일 토큰으로 전송하도록 수정
</br>
- 
</br>
- 
</br>
=> [BE][UP-197] 이메일 API 토큰 파라미터로 수정

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java
- [UP-191] 
</br>
- 
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] tmdb에 없는 영화 제외

src/main/java/com/ureca/picky_be/base/business/lineReview/LineReviewService.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/LineReviewProjection.java, src/main/java/com/ureca/picky_be/base/business/lineReview/dto/ReadLineReviewResp.java, src/main/java/com/ureca/picky_be/base/implementation/lineReview/LineReviewManager.java, src/main/java/com/ureca/picky_be/base/persistence/lineReview/LineReviewRepository.java
- [UP-#](url)
</br>
- 한줄평 좋아요 순 수정
</br>
- 한줄평 좋아요 순 수정
</br>
- 
</br>
=> fix : 한줄평 좋아요 순

src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieProjection.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSimpleMovieResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/PlaylistDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
- [UP-200] #198 
</br>
- Top 10, 장르별 영화, 플레이리스트 조회에 댓글 수 구현
- 관련 DTO API 수정(전체 플레이리스트 조회, 영화 리스트 조회)
</br>
- 워낙 많이 연관된 쿼리이기에 수정으로 인해 타 API 및 기능에 영향이 갈 수 있습니다.
- 많은 이상 방지를 위해 코드 리뷰 부탁
</br>
- 
</br>
=> [BE][UP-200] Top 10, 장르별 영화, 플레이리스트 조회에 댓글 수 구현

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/base/business/movie/dto/GetSearchMoviesResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/MovieDtoMapper.java, src/main/java/com/ureca/picky_be/base/implementation/movie/MovieManager.java, src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java
- [UP-#](url)#197 
</br>
- 엘라스틱 서치 장르, 국가, 반환
</br>
- 엘라스틱 서치 장르, 국가, 반환
</br>
- 엘라스틱 서치 장르, 국가, 반환
</br>
=> [BE][UP-199] 엘라스틱 서치 장르, 국가, 반환

src/main/java/com/ureca/picky_be/base/business/board/BoardService.java, src/main/java/com/ureca/picky_be/base/business/board/dto/BoardProjection.java, src/main/java/com/ureca/picky_be/base/business/board/dto/boardDto/GetBoardInfoResp.java, src/main/java/com/ureca/picky_be/base/implementation/mapper/BoardDtoMapper.java, src/main/java/com/ureca/picky_be/base/persistence/board/BoardRepository.java
- [UP-198] #192 
</br>
- 최신 게시글 조회
- 특정 영화에 대한 게시글 조회
- 마이페이지 닉네임을 통한 조회
- 위 3개 출력에 상영일자, 장르 id들 출력
</br>
- 조회 API 3개에 대해서 반영했으나 연관된 것들이 많아 언제든 이상 발생하면 알려주세요
</br>
- 
</br>
=> [BE][UP-198] 무비로그 조회시, 상영 일자 , 장르들 출력

src/main/java/com/ureca/picky_be/base/business/movie/MovieService.java, src/main/java/com/ureca/picky_be/elasticsearch/document/movie/MovieDocument.java
- [UP-#](url) #192 
</br> 
- 엘라스틱 서치 오토 세이브시 장르 저장
</br>
- 엘라스틱 서치 오토 세이브시 장르 저장
</br>
- 엘라스틱 서치 오토 세이브시 장르 저장
</br>
=> [BE][UP-199] 엘라스틱 서치 오토 세이브시 장르 저장

src/main/java/com/ureca/picky_be/base/business/follow/FollowService.java, src/main/java/com/ureca/picky_be/base/implementation/follow/FollowManager.java, src/main/java/com/ureca/picky_be/base/persistence/follow/FollowRepository.java, src/main/java/com/ureca/picky_be/base/presentation/controller/follow/FollowController.java
- [UP-201] #203 
</br>
- 마이페이지 닉네임 기반으로 사용자 팔로워, 팔로잉 무한스크롤 조회
</br>
- 
</br>
- 
</br>
=> [BE][UP-201] 팔로워, 팔로잉 무한스크롤 조회

src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
- [UP-191]
</br>
- 
</br>
- 
</br>
- 
</br>
=> [BE][UP-191] 카다시안 곱 수정

src/main/java/com/ureca/picky_be/base/persistence/movie/MovieRepository.java
- [UP-#](url)
</br>
- 
</br>
- 
</br>
- 
</br>
=> fix: 카다시안 곱 수정

src/main/java/com/ureca/picky_be/base/presentation/controller/admin/AdminPlaylistController.java
- [UP-#](url)
</br>
- 
</br>
- 
</br>
- 
</br>
=> fix: 플레이리스트 추가 로직 수정
